---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 7000, host: 7000}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[phabricator::default]
    attributes:
